# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 07:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morepractice', '0003_auto_20170728_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='last_accessed',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 1, 10, 57, 34, 476011)),
        ),
    ]
