# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 09:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morepractice', '0005_auto_20170804_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='last_accessed',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 12, 1, 1, 210871)),
        ),
    ]
