# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_group', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_group_fines_interest',
            old_name='name',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='main_group_loan',
            old_name='name',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='main_group_merrygoround',
            old_name='name',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='unga',
            old_name='name',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='unga_fines_interests',
            old_name='name',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='unga_loan',
            old_name='name',
            new_name='member',
        ),
        migrations.AddField(
            model_name='main_group_fines_interest',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unga_fines_interests',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
    ]
