# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_group', '0002_auto_20170809_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupday',
            name='id',
        ),
        migrations.AlterField(
            model_name='groupday',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unga',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
