# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_group', '0003_auto_20170809_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unga',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
