# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_group', '0004_auto_20170809_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_group_merrygoround',
            name='has_paid',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='unga',
            name='has_paid',
            field=models.BooleanField(),
        ),
    ]
