# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('self_group', '0006_auto_20170809_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_group_merrygoround',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merry_set', to='self_group.Groupday'),
        ),
    ]
