# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('self_group', '0009_auto_20170810_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_group_fines_interest',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupfines_set', to='self_group.Groupday'),
        ),
        migrations.AlterField(
            model_name='main_group_fines_interest',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupfines_set', to='self_group.Member'),
        ),
        migrations.AlterField(
            model_name='main_group_loan',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouploan_set', to='self_group.Groupday'),
        ),
        migrations.AlterField(
            model_name='main_group_loan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouploan_set', to='self_group.Member'),
        ),
        migrations.AlterField(
            model_name='main_group_loan_proress',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouploanprocess_set', to='self_group.Groupday'),
        ),
        migrations.AlterField(
            model_name='main_group_loan_proress',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouploanprocess_set', to='self_group.Main_group_loan'),
        ),
        migrations.AlterField(
            model_name='main_group_merrygoround',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merry_set', to='self_group.Member'),
        ),
        migrations.AlterField(
            model_name='unga',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unga_set', to='self_group.Groupday'),
        ),
        migrations.AlterField(
            model_name='unga',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unga_set', to='self_group.Member'),
        ),
        migrations.AlterField(
            model_name='unga_fines_interests',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ungafines_set', to='self_group.Groupday'),
        ),
        migrations.AlterField(
            model_name='unga_fines_interests',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ungafines_set', to='self_group.Member'),
        ),
        migrations.AlterField(
            model_name='unga_loan',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ungaloan_set', to='self_group.Groupday'),
        ),
        migrations.AlterField(
            model_name='unga_loan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ungaloan_set', to='self_group.Member'),
        ),
        migrations.AlterField(
            model_name='unga_loan_progress',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ungaloanprogress_set', to='self_group.Groupday'),
        ),
        migrations.AlterField(
            model_name='unga_loan_progress',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ungaloanprogress_set', to='self_group.Unga_loan'),
        ),
    ]
